# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6feae180c1212d851f628defff98d13402f1be384c6b28dfd0f9856463876b0a4b6299fb2afafb39271545042562b844106a859cdea68368b933f39b14e828c0

test:
  secret_key_base: b7f743c40b89259b2b9354172728d3fa0389b8ddc8e42b07bfbed8f52d0156b00e5a5001132ee1e67de5e32097fc458927f62b5dd021147bd9c620ca2ad8df55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
